# Generated by Django 4.0 on 2022-04-23 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('view_private_posts', 'Can view private posts')]},
        ),
    ]
